#!/usr/bin/env bash
# Stop hook: opt-in guard, then read the session_id and transcript_path from
# the hook payload, stage the workspace, and commit with a rich message
# generated by build-message.py (prompt + response excerpt + token/tool/timing
# stats as git trailers). Falls back to a minimal message if the helper or
# transcript is unavailable.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/_paths.sh"

history_is_enabled || exit 0
[ -d "$GIT_DIR" ] || exit 0

# Pull session_id and transcript_path out of the payload in one python call.
HOOK_PAYLOAD=$(cat)
read_field() {
  HIST_PAYLOAD="$HOOK_PAYLOAD" python3 -c '
import json, os, sys
try:
    data = json.loads(os.environ["HIST_PAYLOAD"])
except Exception:
    data = {}
sys.stdout.write(str(data.get(sys.argv[1]) or ""))
' "$1" 2>/dev/null
}
SESSION_ID=$(read_field session_id)
TRANSCRIPT_PATH=$(read_field transcript_path)

PROMPT_FILE="$GIT_DIR/.last-prompt-${SESSION_ID:-unknown}"

git --git-dir="$GIT_DIR" --work-tree="$PWD" add --all

# Number of files changed compared to HEAD (or against the empty tree on the
# very first commit). We tolerate the empty-repo case by counting cached
# entries instead.
FILES_CHANGED=$(git --git-dir="$GIT_DIR" --work-tree="$PWD" diff --cached --name-only 2>/dev/null | sed '/^$/d' | wc -l | tr -d ' ')
[ -z "$FILES_CHANGED" ] && FILES_CHANGED=0

MSG_FILE=$(mktemp "${TMPDIR:-/tmp}/history-msg.XXXXXX")
build_minimal() {
  # Subject = prompt (or "turn" fallback) + Session trailer if known.
  local prompt="turn"
  [ -s "$PROMPT_FILE" ] && prompt=$(cat "$PROMPT_FILE")
  {
    printf '%s\n' "$prompt"
    [ -n "$SESSION_ID" ] && { printf '\nSession: %s\n' "$SESSION_ID"; }
    [ "$FILES_CHANGED" -ge 0 ] && printf 'Files-Changed: %s\n' "$FILES_CHANGED"
  } > "$MSG_FILE"
}

if ! python3 "$SCRIPT_DIR/build-message.py" \
    --transcript "$TRANSCRIPT_PATH" \
    --session "$SESSION_ID" \
    --prompt-file "$PROMPT_FILE" \
    --files-changed "$FILES_CHANGED" > "$MSG_FILE" 2>/dev/null; then
  build_minimal
fi

# Empty message would make git refuse the commit.
[ -s "$MSG_FILE" ] || build_minimal

git --git-dir="$GIT_DIR" --work-tree="$PWD" commit \
  --allow-empty -F "$MSG_FILE" --quiet 2>/dev/null

rm -f "$MSG_FILE"

# Detached auto-push. Only fires if this workspace opted in via push-enable
# AND a remote is configured. Pushes to host/<hostname> so each machine
# appends linearly without merging another machine's branch. stdout/stderr
# go to push.log (truncated each fire); the `status` skill surfaces
# ahead-count, which makes a stuck push visible without reading the log.
if history_auto_push_enabled && [ -n "$(history_remote_url)" ]; then
  PUSH_BRANCH=$(history_branch_for_host)
  PUSH_LOG=$(history_push_log_path)
  (
    git --git-dir="$GIT_DIR" push origin "HEAD:refs/heads/$PUSH_BRANCH"
  ) </dev/null >"$PUSH_LOG" 2>&1 &
  disown $! 2>/dev/null || true
fi

exit 0
